sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t prathamesh12/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true prathamesh12/docker-react npm run test -- --coverage --watchAll=false
