sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t prathamesh12/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true prathamesh12/dockerreact npm run test -- --watchAll=false
