sudo: required
language: generic

services: 
  - docker

before_install:
  - docker build -t prathamesh12/dockerreact -f Dockerfile.dev .

script:
  - docker run -e CI=true prathamesh12/dockerreact npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  name: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-812122552477"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

